# Generated by Django 4.1.7 on 2023-03-16 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accounts',
            old_name='name',
            new_name='username',
        ),
    ]
