# Generated by Django 4.1.7 on 2023-03-17 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rename_name_accounts_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounts',
            name='license_key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
