# Generated by Django 4.1.7 on 2023-03-18 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gpt_core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mygptapp',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
