# Generated by Django 4.1.7 on 2023-03-18 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gpt_core', '0002_alter_mygptapp_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='mygptapp',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
