# Generated by Django 4.1.7 on 2023-03-18 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gpt_core', '0003_mygptapp_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='mygptapp',
            name='private',
            field=models.BooleanField(default=False),
        ),
    ]
